# Generated by Django 5.0.3 on 2024-03-24 13:44

import autoslug.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='post_title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='post_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
