# Generated by Django 5.0.3 on 2024-03-24 14:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_news_slug_alter_service_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='post_title', unique=True),
        ),
    ]
