# Generated by Django 5.0.3 on 2024-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='post_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
